# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Name',
            field=models.CharField(default=b'undef', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
