# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tickettype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('tike_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket_type',
            name='event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='show',
            name='supervisor',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='show',
            name='tickets_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='Name',
            field=models.CharField(default=b'0', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'2017-10-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(verbose_name=b'2017-10-24'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pin',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ticket_type',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show'),
        ),
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(default=b'0', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickapp.profile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(default=b'0', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickapp.tickettype'),
        ),
    ]
