# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0002_auto_20180524_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickapp.profile'),
        ),
    ]
