# Generated by Django 2.0.4 on 2018-07-27 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0004_auto_20180524_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='event',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='tickapp.Show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(verbose_name='2018-07-27'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster',
            field=models.ImageField(upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='show',
            name='supervisor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='video',
            field=models.FileField(upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default='2018-07-27'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
