# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-11-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickapp', '0005_auto_20180727_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Name',
            field=models.CharField(default=b'undef', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(verbose_name=b'2018-11-25'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=b'2018-11-25'),
        ),
    ]
